- name: Update and prepare
  hosts: hosts
  become: true
  remote_user: root
  roles:
    - user-setup
  tags:
    - user-setup

- name: Configure UFW
  hosts: hosts
  become: true
  remote_user: root
  roles:
    - ufw
  tags:
    - ufw

- name: Install pip
  hosts: hosts
  become: true
  remote_user: nerf
  roles:
    - pip
  tags:
    - pip

- name: Install Ghost and friends
  hosts: hosts
  become: true
  remote_user: sffresch
  roles:
    - ghost
  tags:
    - ghost

- name: Install Airflow
  hosts: hosts
  become: true
  remote_user: root
  roles:
    - airflow
  tags:
    - airflow