db:
  host: localhost
  port: 3306
  name: airflow_db
  user: airflow_user
airflow:
  cfg:
    - section: core
      key: logging_level
      value: WARN
    - section: core
      key: load_examples
      value: False
    - section: core
      key: executor
      value: LocalExecutor
    - section: core
      key: load_default_connections
      value: False
    - section: webserver
      key: authenticate
      value: True
    - section: webserver
      key: auth_backend
      value: airflow.contrib.auth.backends.password_auth
  path: ~/airflow/airflow.cfg