- name: Set state of ufw
  ufw:
    state: "{{ vars.state }}"

- name: Set ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    delete: "{{ item.delete }}"
  with_items: "{{ vars.rules }}"