- name: Ensure .ssh directory exists
  file:
    dest: /root/.ssh/
    mode: 0700
    owner: root
    state: directory

- name: Install ssh private key
  copy:
    src: "{{ lookup('file', '/Users/frankeschner/.ssh/id_rsa_sffresch') }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
    owner: user

- name: Clone desired git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ vars.gits }}"